sudo: false
language: cpp
env:
	- COMPILER=g++
	- COMPILER=clang++

compiler:
	- g++
	- clang++

install:
	- g++ --version
	- clang++ --version

script:
	- ls
	- cd advanced-programming/lectures/01_intro/
	- make
