sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - clang-3.8

compiler:
  - g++-6
  - clang++-3.8

script:
  - c++ --version
  - $CXX --version
  - g++ --version
  # - make CXX=$CXX
